<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaLogRepository extends \Doctrine\ORM\EntityRepository {

}
