<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaGoogleAdwordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaGoogleAdwordsRepository extends \Doctrine\ORM\EntityRepository
{
}
