<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaGoogleAnalyticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaGoogleAnalyticsRepository extends \Doctrine\ORM\EntityRepository
{
}
