<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaFeedSourceBiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaFeedSourceBiRepository extends \Doctrine\ORM\EntityRepository
{
}
