<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaSalesForceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaSalesForceRepository extends \Doctrine\ORM\EntityRepository
{
}
