<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaCategoryGoogleMerchantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaCategoryGoogleMerchantRepository extends \Doctrine\ORM\EntityRepository
{
}
