<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * LineaBiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaVentaSourceBiRepository extends \Doctrine\ORM\EntityRepository
{
}
