<?php

namespace FeedGroupaliaBundle\Repository;

/**
 * MapeoGoogleCategoryWithGroupaliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapeoGoogleCategoryWithGroupaliaRepository extends \Doctrine\ORM\EntityRepository
{
}
