<?php

namespace AnalyticsBundle\Repository;

/**
 * LineaAnalayticsDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaAnalayticsDetalleRepository extends \Doctrine\ORM\EntityRepository {
    
    /**
     * 
     * @param int $linea_analytics_id
     * @return array()
     */
    public function getDatosAnalyticsByLineaAnalyticsId($linea_analytics_id) {
        $connection = $this->getEntityManager()->getConnection();
        $stmt  = $connection->prepare('select SUM(ga_users), SUM(ga_new_users),SUM(ga_bounces),SUM(ga_unique_pageviews),ROUND(AVG(ga_bounce_rate),2)
from linea_analaytics_detalle
where linea_analytics_id ='.$linea_analytics_id);
        $stmt->execute();
        return $stmt->fetchAll();
    }

}
