<?php

namespace AnalyticsBundle\Repository;

/**
 * LineaAnalyticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaAnalyticsRepository extends \Doctrine\ORM\EntityRepository
{
}
