<?php

namespace PixelTrackingBundle\Repository;

/**
 * LineaTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtribucionRepository extends \Doctrine\ORM\EntityRepository
{
}
